# Generated by Django 5.2.1 on 2025-05-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=150,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                ("action", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "is_pleasant_habit",
                    models.BooleanField(verbose_name="Признак приятной привычки"),
                ),
                ("periodicity", models.FloatField(default=1)),
                (
                    "award",
                    models.CharField(
                        blank=True, null=True, verbose_name="Вознаграждение"
                    ),
                ),
                ("complete_time", models.FloatField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
