# Generated by Django 5.2.1 on 2025-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="complete_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
