# Generated by Django 5.2.1 on 2025-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_complete_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Укажите действие",
                max_length=150,
                null=True,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="complete_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Время на выполнение в секундах"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="Признак публичности"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.FloatField(
                default=1,
                help_text="Количество дней выполнения в неделю",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Укажите время выполнения привычки",
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
